version: "3.8"

services:
  web:
    image: harusame0616/hallog-web-dev
    ports:
      - 3010:3000
    volumes:
      - ./web/project:/project
      - web-node_modules:/project/node_modules
      - web-dot-nuxt:/project/.nuxt
volumes:
  web-node_modules:
  web-dot-nuxt:
